-- Baseline 1/5: extensions, schemas, import metadata, reference codes and raw records.
-- Run the complete baseline with: python -m db.migrate
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE SCHEMA IF NOT EXISTS meta;
CREATE SCHEMA raw;
CREATE SCHEMA src_scb;
CREATE SCHEMA src_bolagsverket;
CREATE SCHEMA core;
CREATE SCHEMA app;
CREATE SCHEMA mart;

CREATE TABLE meta.source (
    code text PRIMARY KEY,
    name text NOT NULL
);
INSERT INTO meta.source VALUES
    ('scb_api', 'SCB API'), ('scb_bulk', 'SCB bulk'),
    ('bolagsverket', 'Bolagsverket bulk'), ('legacy', 'Migrated v1 data');

CREATE TABLE meta.ingestion_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source text NOT NULL REFERENCES meta.source(code),
    dataset text NOT NULL DEFAULT 'company',
    started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    finished_at timestamptz,
    source_as_of_date date,
    filename text,
    file_checksum text,
    schema_version text NOT NULL DEFAULT '2',
    metadata jsonb NOT NULL DEFAULT '{}',
    records_seen bigint NOT NULL DEFAULT 0 CHECK (records_seen >= 0),
    records_new bigint NOT NULL DEFAULT 0 CHECK (records_new >= 0),
    records_changed bigint NOT NULL DEFAULT 0 CHECK (records_changed >= 0),
    records_skipped bigint NOT NULL DEFAULT 0 CHECK (records_skipped >= 0),
    last_row_number bigint NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'running'
        CHECK (status IN ('running', 'done', 'failed', 'interrupted')),
    error text
);
CREATE INDEX ingestion_run_file ON meta.ingestion_run(source, file_checksum, id DESC);

CREATE TABLE meta.data_quality_issue (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ingestion_run_id bigint NOT NULL REFERENCES meta.ingestion_run(id),
    row_number bigint,
    issue_code text NOT NULL,
    detail text NOT NULL,
    observed_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- Code domains keep different authorities' codes apart. Codes are identifiers, not numbers.
CREATE TABLE meta.code (
    source text NOT NULL REFERENCES meta.source(code),
    domain text NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    parent_code text,
    PRIMARY KEY (source, domain, code)
);

-- Stable Bolagsverket organization-form labels. Geography is seeded from the
-- checked-in SCB code tables by db.migrate after the SQL transaction.
INSERT INTO meta.code(source, domain, code, name) VALUES
    ('bolagsverket', 'organization_form_code', 'AB-ORGFO', 'Aktiebolag'),
    ('bolagsverket', 'organization_form_code', 'BAB-ORGFO', 'Bankaktiebolag'),
    ('bolagsverket', 'organization_form_code', 'BF-ORGFO', 'Bostadsförening'),
    ('bolagsverket', 'organization_form_code', 'BFL-ORGFO', 'Utländsk banks filial'),
    ('bolagsverket', 'organization_form_code', 'BRF-ORGFO', 'Bostadsrättsförening'),
    ('bolagsverket', 'organization_form_code', 'E-ORGFO', 'Enskild näringsverksamhet'),
    ('bolagsverket', 'organization_form_code', 'EB-ORGFO', 'Enkla bolag'),
    ('bolagsverket', 'organization_form_code', 'EEIG-ORGFO', 'Europeisk ekonomisk intressegruppering'),
    ('bolagsverket', 'organization_form_code', 'EGTS-ORGFO', 'Europeisk gruppering för territoriellt samarbete'),
    ('bolagsverket', 'organization_form_code', 'EK-ORGFO', 'Ekonomisk förening'),
    ('bolagsverket', 'organization_form_code', 'FAB-ORGFO', 'Försäkringsaktiebolag'),
    ('bolagsverket', 'organization_form_code', 'FF-ORGFO', 'Försäkringsförmedlare'),
    ('bolagsverket', 'organization_form_code', 'FL-ORGFO', 'Filial'),
    ('bolagsverket', 'organization_form_code', 'FOF-ORGFO', 'Försäkringsförening'),
    ('bolagsverket', 'organization_form_code', 'HB-ORGFO', 'Handelsbolag'),
    ('bolagsverket', 'organization_form_code', 'I-ORGFO', 'Ideell förening som bedriver näringsverksamhet'),
    ('bolagsverket', 'organization_form_code', 'KB-ORGFO', 'Kommanditbolag'),
    ('bolagsverket', 'organization_form_code', 'KHF-ORGFO', 'Kooperativ hyresrättsförening'),
    ('bolagsverket', 'organization_form_code', 'MB-ORGFO', 'Medlemsbank'),
    ('bolagsverket', 'organization_form_code', 'OFB-ORGFO', 'Ömsesidigt försäkringsbolag'),
    ('bolagsverket', 'organization_form_code', 'OTPB-ORGFO', 'Ömsesidigt tjänstepensionsbolag'),
    ('bolagsverket', 'organization_form_code', 'S-ORGFO', 'Stiftelse som bedriver näringsverksamhet'),
    ('bolagsverket', 'organization_form_code', 'SB-ORGFO', 'Sparbank'),
    ('bolagsverket', 'organization_form_code', 'SCE-ORGFO', 'Europakooperativ'),
    ('bolagsverket', 'organization_form_code', 'SE-ORGFO', 'Europabolag'),
    ('bolagsverket', 'organization_form_code', 'SF-ORGFO', 'Sambruksförening'),
    ('bolagsverket', 'organization_form_code', 'TPAB-ORGFO', 'Tjänstepensionsaktiebolag'),
    ('bolagsverket', 'organization_form_code', 'TPF-ORGFO', 'Tjänstepensionsförening'),
    ('bolagsverket', 'organization_form_code', 'TSF-ORGFO', 'Trossamfund som bedriver näringsverksamhet');

-- JSON (not JSONB) preserves escaped NULs from malformed source text.
-- Keep the original files too: payload is an exact decoded record, not the original bytes.
CREATE TABLE raw.company_record (
    source text NOT NULL REFERENCES meta.source(code),
    ingestion_run_id bigint NOT NULL REFERENCES meta.ingestion_run(id),
    row_number bigint NOT NULL,
    source_file text,
    payload json NOT NULL,
    raw_hash text NOT NULL,
    observed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (source, ingestion_run_id, row_number)
) PARTITION BY LIST (source);
CREATE TABLE raw.scb_api_company PARTITION OF raw.company_record FOR VALUES IN ('scb_api');
CREATE TABLE raw.scb_bulk_company PARTITION OF raw.company_record FOR VALUES IN ('scb_bulk');
CREATE TABLE raw.bolagsverket_company PARTITION OF raw.company_record FOR VALUES IN ('bolagsverket');
CREATE TABLE raw.legacy_company PARTITION OF raw.company_record FOR VALUES IN ('legacy');

CREATE FUNCTION raw.reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Raw records are immutable; import a new observation instead';
END;
$$;
CREATE TRIGGER immutable_company_record BEFORE UPDATE OR DELETE ON raw.company_record
    FOR EACH ROW EXECUTE FUNCTION raw.reject_mutation();

REVOKE ALL ON SCHEMA raw, src_scb, src_bolagsverket, core, meta FROM PUBLIC;
