-- Baseline 2/5: canonical company, history, change, event and workplace models.

CREATE TABLE core.company (
    company_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type text NOT NULL CHECK (entity_type IN ('organization', 'person', 'other')),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE core.company_identifier (
    company_id bigint NOT NULL REFERENCES core.company(company_id),
    identity_type text NOT NULL,
    identity_value text NOT NULL,
    PRIMARY KEY (identity_type, identity_value),
    UNIQUE (company_id, identity_type),
    CHECK (identity_type <> 'ORGNR' OR identity_value ~ '^[0-9]{10}$'),
    CHECK (identity_type <> 'PERSON' OR identity_value ~ '^[0-9]{12}$'),
    CHECK (identity_type <> 'PERSON_SHORT' OR identity_value ~ '^[0-9]{10}$')
);
CREATE INDEX company_identifier_company ON core.company_identifier(company_id);
CREATE INDEX company_identifier_person_short ON core.company_identifier(right(identity_value, 10)) WHERE identity_type = 'PERSON';

CREATE TABLE core.company_source_key (
    source text NOT NULL REFERENCES meta.source(code),
    source_key text NOT NULL,
    source_subkey text NOT NULL DEFAULT '',
    company_id bigint NOT NULL REFERENCES core.company(company_id),
    PRIMARY KEY (source, source_key, source_subkey)
);
CREATE INDEX company_source_key_company ON core.company_source_key(company_id, source);

CREATE TABLE core.company_state_history (
    state_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES core.company(company_id),
    company_name text,
    registered_name text,
    co_address text,
    postal_address text,
    postal_code text,
    postal_city text,
    seat_municipality_code text,
    seat_county_code text,
    region_code text,
    workplace_count integer CHECK (workplace_count >= 0),
    employee_size_code text,
    activity_status_code text,
    legal_entity_status_code text,
    tax_registry_status_code text,
    legal_form_code text,
    advertising_status_code text,
    bulk_advertising_status_code text,
    mail_status_code text,
    start_date date,
    end_date date,
    scb_registration_date date,
    primary_industry_code text,
    industry_section_code text,
    trade_indicator text,
    turnover_year smallint,
    turnover_class_code text,
    turnover_detail_class_code text,
    ownership_category_code text,
    phone text,
    email text,
    private_public_code text,
    employer_status_code text,
    vat_status_code text,
    f_tax_status_code text,
    company_state_code text,
    registered_name_count integer CHECK (registered_name_count >= 0),
    sector_code text,
    sme_size_code text,
    female_share numeric(5,2) CHECK (female_share BETWEEN 0 AND 100),
    male_share numeric(5,2) CHECK (male_share BETWEEN 0 AND 100),
    owner_country_code text,
    owner_name text,
    foreign_ownership_code text,
    labels jsonb NOT NULL DEFAULT '{}',
    provenance jsonb NOT NULL DEFAULT '{}',
    state_hash text NOT NULL,
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    created_by_run_id bigint NOT NULL REFERENCES meta.ingestion_run(id),
    organization_form_code text,
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);
CREATE UNIQUE INDEX company_state_current ON core.company_state_history(company_id) WHERE valid_to IS NULL;
CREATE INDEX company_state_as_of ON core.company_state_history(company_id, valid_from DESC);
CREATE INDEX company_name_search ON core.company_state_history USING gin (company_name gin_trgm_ops) WHERE valid_to IS NULL;
CREATE INDEX company_registered_name_search ON core.company_state_history USING gin (registered_name gin_trgm_ops) WHERE valid_to IS NULL;
CREATE INDEX company_geography ON core.company_state_history(seat_county_code, seat_municipality_code) WHERE valid_to IS NULL;
CREATE INDEX company_activity ON core.company_state_history(activity_status_code) WHERE valid_to IS NULL;
CREATE INDEX company_primary_industry ON core.company_state_history(primary_industry_code) WHERE valid_to IS NULL;
CREATE INDEX company_employees ON core.company_state_history(employee_size_code) WHERE valid_to IS NULL;
CREATE INDEX company_turnover ON core.company_state_history(turnover_class_code) WHERE valid_to IS NULL;
CREATE INDEX company_current_organization_form ON core.company_state_history(organization_form_code) WHERE valid_to IS NULL;
CREATE INDEX company_current_municipality ON core.company_state_history(seat_municipality_code) WHERE valid_to IS NULL;
CREATE INDEX company_current_name_order ON core.company_state_history(company_name ASC NULLS LAST, company_id) WHERE valid_to IS NULL;
CREATE INDEX company_current_name_order_desc ON core.company_state_history(company_name DESC NULLS LAST, company_id) WHERE valid_to IS NULL;
CREATE INDEX company_current_registered_name_order ON core.company_state_history(registered_name ASC NULLS LAST, company_id) WHERE valid_to IS NULL;
CREATE INDEX company_current_postal_city_search ON core.company_state_history USING gin (postal_city gin_trgm_ops) WHERE valid_to IS NULL;
CREATE INDEX company_current_postal_code_digits ON core.company_state_history((regexp_replace(postal_code, '\s+', '', 'g'))) WHERE valid_to IS NULL;
CREATE INDEX company_current_name_prefix ON core.company_state_history(lower(company_name) text_pattern_ops, company_id) WHERE valid_to IS NULL;
CREATE INDEX company_current_registered_name_prefix ON core.company_state_history(lower(registered_name) text_pattern_ops, company_id) WHERE valid_to IS NULL;
CREATE INDEX company_current_name_tokens ON core.company_state_history USING gin (to_tsvector('simple', coalesce(company_name, ''))) WHERE valid_to IS NULL;
CREATE INDEX company_current_registered_name_tokens ON core.company_state_history USING gin (to_tsvector('simple', coalesce(registered_name, ''))) WHERE valid_to IS NULL;
CREATE VIEW core.company_current AS SELECT * FROM core.company_state_history WHERE valid_to IS NULL;

-- A set of industries belongs to a state version and shares its validity interval.
CREATE TABLE core.company_industry (
    state_id bigint NOT NULL REFERENCES core.company_state_history(state_id),
    rank smallint NOT NULL CHECK (rank BETWEEN 1 AND 5),
    sni_code text NOT NULL CHECK (sni_code ~ '^[0-9]{5}$'),
    sni_version text NOT NULL,
    source text NOT NULL REFERENCES meta.source(code),
    PRIMARY KEY (state_id, rank),
    UNIQUE (state_id, sni_code)
);
CREATE INDEX company_industry_sni ON core.company_industry(sni_version, sni_code, state_id);
CREATE VIEW core.company_industry_history AS
SELECT s.company_id, i.*, s.valid_from, s.valid_to, i.rank = 1 AS is_primary
FROM core.company_industry i JOIN core.company_state_history s USING (state_id);

CREATE TABLE core.company_change (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES core.company(company_id),
    state_id bigint REFERENCES core.company_state_history(state_id),
    field_name text NOT NULL,
    old_value text,
    new_value text,
    old_label text,
    new_label text,
    detected_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    ingestion_run_id bigint REFERENCES meta.ingestion_run(id),
    importance smallint NOT NULL DEFAULT 1
);
CREATE INDEX company_change_timeline ON core.company_change(company_id, detected_at DESC);
CREATE TABLE core.company_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES core.company(company_id),
    event_type text NOT NULL,
    title text NOT NULL,
    description text,
    effective_at date,
    detected_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    ingestion_run_id bigint REFERENCES meta.ingestion_run(id),
    company_change_ids bigint[],
    importance smallint NOT NULL DEFAULT 1
);
CREATE INDEX company_event_timeline ON core.company_event(company_id, detected_at DESC);

CREATE TABLE core.workplace (
    workplace_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES core.company(company_id),
    cfar_number text NOT NULL UNIQUE CHECK (cfar_number ~ '^[0-9]{8}$'),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX workplace_company ON core.workplace(company_id);
CREATE TABLE core.workplace_state_history (
    state_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    workplace_id bigint NOT NULL REFERENCES core.workplace(workplace_id),
    name text,
    postal_address text,
    postal_code text,
    postal_city text,
    visiting_address text,
    municipality_code text,
    county_code text,
    status_code text,
    employee_size_code text,
    state_hash text NOT NULL,
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    created_by_run_id bigint NOT NULL REFERENCES meta.ingestion_run(id),
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);
CREATE UNIQUE INDEX workplace_state_current ON core.workplace_state_history(workplace_id) WHERE valid_to IS NULL;
CREATE VIEW core.workplace_current AS SELECT * FROM core.workplace_state_history WHERE valid_to IS NULL;
